name: Bug report
description: Report a problem with the site or content.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect vs what happened?
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Page / file path
      placeholder: "e.g., notes/beginner/cs/what-is-a-computer.md"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: false
