name: Content request
description: Request a new note, lab, or cheatsheet.
title: "[Content]: "
labels: ["content"]

body:
  - type: dropdown
    id: type
    attributes:
      label: Content type
      options:
        - Note
        - Lab
        - Cheatsheet
    validations:
      required: true

  - type: input
    id: topic
    attributes:
      label: Topic / title
      placeholder: "e.g., Beginner Git: Branching basics"
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: What should it cover?
      description: Bullet points are fine.
    validations:
      required: true
