name: New note proposal
description: Propose a new note with scope and placement in CORE.
title: "[Note]: "
labels: ["note"]

body:
  - type: input
    id: path
    attributes:
      label: Proposed file path
      placeholder: "e.g., notes/beginner/git/git-branches.md"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: 2–5 sentences explaining what the note teaches and prerequisites.
    validations:
      required: true

  - type: textarea
    id: refs
    attributes:
      label: Sources / references
      description: Links, books, or specs backing this note.
    validations:
      required: false
